name: CI

on:
    - push
    - pull_request

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            os: [macos-13]
            ruby:
                - 2.7
                - '3,0'
                - 3.2
    runs-on: ${{ matrix.os }}

    steps:
        - uses: actions/checkout@v2

        - name: Set up Ruby 3.0
          uses: actions/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cash: true

        - run: make install
        - run: make lint
        - run: male test
